IMDbTraktSyncer/IMDbTraktSyncer.py

Ignore items with no IMDb ID
Use alternate method like show/movie name + year to set ratings with no IMDb ID is available
https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/4

Items with no IMDb ID breaking script

---

IMDbTraktSyncer/checkChromedriver.py
setup.py

- Modify `checkChromedrivery.py` to ensure that the appropriate version of `chromedriver-py` is installed based on the current installed Chrome version, and it handles different operating systems to retrieve the Chrome version accordingly. 
_Tested and working on Windows. Untested on Linux and MacOS. If this update causes you issues please open an issue and describe the error you are receiving and your operating system._

Improve chromedriver version check and automatically install correct chromedriver version

---

IMDBTraktSyncer/traktData.py
setup.py

- Script will now correctly pull Trakt username via url slug instead of username directly. This will fix the script breaking for users where their username is different than their username url slug.

Fix for script failing with some Trakt usernames

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/checkChromedriver.py
setup.py

- Fix for chromedriver version check syntax error. This was preventing the correct chromedriver version from being installed.
- Minor spelling changes

Fix for chromedriver version check syntax error + minor spelling changes

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
setup.py

- Fix for timeout error breaking script when rating some items on IMDB. https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/46#issuecomment-1594097658
- Modified setting `IMDB ratings` in `IMDBTraktSyncer.py` so the entire code block is handled with error exceptions to avoid the script breaking when there are errors rating an item. (404 errors causing timeout exceptions etc).
- Modified getting `IMDB reviews` in `imdbData.py` so the entire code block is handled with error exceptions to avoid the script breaking if there are errors finding and clicking the reviews link.

Fix for timeout error breaking script when rating some items on IMDB

---

IMDBTraktSyncer/IMDBTraktSyncer.py
setup.py

- Fix for IMDB actions failing when `Show reference view with full cast and crew (advanced view)` setting is enabled on IMDB https://www.imdb.com/preferences/general. Actions that were effected: setting IMDB ratings, adding items to IMDB watchlist, removing items from IMDB watchlist.
- Fix for https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/56
- Potential fix for https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/46

Fix for IMDB actions failing when reference view setting is enabled on IMDB

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
setup.py

- Added support for updating ratings with most recent rating.
**Note:** For items rated on the same day but with different ratings, the Trakt rating will take priority. This is due to and IMDB limitation. The IMDB ratings csv data only includes the rated date in Y-M-D format without a time.

Add support for updating ratings with most recent rating

---

IMDBTraktSyncer/IMDBTraktSyncer.py
setup.py

- Modify updating ratings logic so that ratings changed on the same day are not overwritten. 
**Note:** Originally in [1.7.0 release](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.7.0) the Trakt rating would take priority for ratings changed on the same day. This was changed in 1.7.1 in order to keep the original functionality where ratings are not overwritten. This will avoid situations where the user updates a rating on IMDB and then it is overwritten with an older Trakt rating on next sync. 
This problem originates from an IMDB limitation. The ratings csv data IMDB provides only includes the rated date in Y-M-D format without a time.

Modify updating ratings logic so that ratings made on the same day are not overwritten

---

IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/checkChromedriver.py
setup.py

Modify chromedriver check fallback method to get the latest release instead of the second latest release. This is due to a change in the [chromedriver api](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints) and as a result the [chromedriver-py releases](https://pypi.org/project/chromedriver-py/#history) have changed.

Modify chromedriver check fallback method

---

IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

Fix for a bug in the script with Trakt authorization. The Trakt auth token expires after 3 months but the script was not handling this correctly. This patch fixes this be correctly reauthenticating with the Trakt refresh token.
Users upgrading to v1.8.0 or later will be prompted to reauthenticate Trakt. After which, the reauthentication process will no longer require further user interaction.

Fix for Trakt authentication

---

IMDBTraktSyncer/traktData.py
setup.py

- Fixed an issue where not all episodes in a show were being counted as watched due to duplicate episode numbers being removed from a list argument. This was resulting in a 100% watched show with multiple seasons not being removed from the users watchlists.
- Fixed an issue where cancelled shows were not being removed from watchlists, this was due to a spelling issue in the Trakt API that uses the string `canceled` instead of `cancelled`. The script now handles both spelling situations.

Improvements for removing watched items from watchlists

---

IMDBTraktSyncer/IMDBTraktSyncer.py
setup.py

Fix for a bug which would cause chrome instances to not shutdown fully. This would occasionally leave some chrome processes to linger after the script completes. 
By invoking `driver.close()` before `driver.quit()` ensures that the headless chrome window(s) are closed properly prior to ending the chrome processes.

Fix for improper chromedriver shutdown

---

IMDBTraktSyncer/IMDBTraktSyncer.py
setup.py

Adds additional method `driver.close()` in order to properly clean up chrome instances when chromedriver shuts down after an IMDB captcha check or login failure.

Improve chromedriver shutdown

---

IMDBTraktSyncer/verifyCredentials.py
setup.py

- Minor text change when prompting the user for `imdb_username`. This field should be the users `email` or `phone number` used for logging into IMDB. 
- This change should help users avoid accidently filling in the wrong info for this field as mentioned in https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/2#issuecomment-1946046445.

Minor change when prompting for IMDB username

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
setup.py

- Fix addresses network related errors with Trakt requests and IMDB page loads. The script will now correctly handle and retry these errors wherever possible. Original bug report: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/108#issuecomment-2540858202
- Fix syntax error as mentioned: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/108#issuecomment-2541188809

Fix for network related Trakt requests and IMDB page load errors + fix syntax error

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/checkVersion.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
setup.py

- Improvements for network related error handling with Trakt requests and IMDB chromedriver page loads. The script should now properly handle all network related errors and retry requests where possible, eliminating many potential errors.
- Replaced `chromedriver-py` requirement with `webdriver-manager`. This removes the need for `checkChromedriver.py`, allows the possibility of multi-browser support and expanded OS compatibility. Users upgrading to v3.0.1 who are not using `chromedriver-py` in other projects can safely uninstall it using `python -m pip uninstall chromedriver-py`.
- Possible fix for https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/104

Improvements for network related error handling, replace chromedriver-py with webdriver-manager & more

---

IMDBTraktSyncer/errorHandling.py
setup.py

- Skip logging and printing 429 rate limit errors to allow faster processing and better readability

Minor improvements for requests 429 rate limit error handling

---

IMDBTraktSyncer/checkVersion.py
setup.py

- Change back to calling `pip` directly to check current `IMDBTraktSyncer` version. If that fails, it falls back to calling `sys.executable -m pip`. Print an unexpected error if all attempts fail, without causing the script to fail.
- Fix for https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/115

Fix for potential failures when checking IMDBTraktSyncer version

---

README.md

The script now downloads and manages the portable "[Chrome for Testing](https://googlechromelabs.github.io/chrome-for-testing/)" browser automatically in the install directory. This makes the package a whole more portable, bypasses issues with some Chrome installs, and allows for possible future implementations of docker support.
The script now uses selenium's new built in tool `selenium manager` to download and manage chromedriver versions. Users upgrading to v3.1.0 can safely uninstall `webdriver-manager` using:
```
python -m pip uninstall webdriver-manager
```
````bash
IMDBTraktSyncer --clear-user-data
IMDBTraktSyncer --clear-cache
IMDBTraktSyncer --uninstall
IMDBTraktSyncer --clean-uninstall
IMDBTraktSyncer --directory
IMDBTraktSyncer --clear-user-data --clear-cache
````

Removed chrome install requirement, added support for arguments and replaced webdriver-manager with selenium's new built in chromedriver manager

---

IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

Fixes an issue where unspecified rate limiting rules were applied for re authenticating Trakt API refresh and access tokens via OAUTH, causing max retry limit error to trigger and breaking all versions 2.0.1 and below.

Fix for Trakt API Re-Authentication

---

IMDBTraktSyncer/authTrakt.py
setup.py

Fixes a new issue where invalid Trakt API tokens did not re-prompt the user to re-authenticate, causing the script to fail.

Fix for updating invalid Trakt API tokens

---

IMDBTraktSyncer/verifyCredentials.py
setup.py

Fixes a bug where the user is prompted again to enter their preferences on each run, due to a bug where certain settings are overwritten in credentials.txt.

Fix-for recurring settings text prompt loop

---

IMDBTraktSyncer/checkChrome.py
pyproject.toml

- Fixes https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/132 moving the extracted chrome directory was causing the script to fail.
- Fixes [#issuecomment-2594902045](https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/132#issuecomment-2594902045) and [#issuecomment-2595089014](https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/132#issuecomment-2595089014) where the extracted Chrome binary was not in the expected directory. And fixes macos/linux comparability when clearing the selenium chromedriver cache.

Fixes for several pathing issues on linux and macos

---

IMDBTraktSyncer/arguments.py
IMDBTraktSyncer/checkChrome.py
pyproject.toml

Potential fix for permissions issue on macos and linux for extracted chromedriver binary where the user does not have the proper read/write/execution permissions

Fix chromedriver permissions issue on macos and linux

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/arguments.py
IMDBTraktSyncer/checkChrome.py
IMDBTraktSyncer/checkVersion.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
pyproject.toml

- Ignore processing items with matching Title, Year and Type, AND have non-matching IMDB IDs. This is to prevent outdated IMDB IDs from Trakt interfering with the comparison logic. This prevents the script from failing to process the same items on each run.
- Improve driver handling, passing both the driver and wait variables and returning them from the get_page_with_retries function to avoid driver instance mismatches and other related errors.

Improve logic when comparing items with outdated IMDB ID + improve driver handling

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
pyproject.toml

- Adjust list data sorting to sort by date. To make sure oldest items are added first.
- Minor bug fixes regarding getting the date values from Trakt API.
- Prevent syncing IMDB watchlist items over the [10,000 limit](https://help.imdb.com/article/imdb/track-movies-tv/lists-faq/GNQMN47VZSE7KW38).

Minor bug fixes, adjust list sorting by date, prevent syncing IMDB watchlist items over the 10,000 limit

---

IMDBTraktSyncer/IMDBTraktSyncer.py

The current code creates a new list to filter by on every iteration.

Use temporary sets and set lookups to speedup filtering

---

IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/checkChrome.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/verifyCredentials.py
pyproject.toml

- Starting on March 4, 2025, the Trakt OAuth access_token expires in 24 hours, instead of 3 months. This pr addresses this new requirement by getting the `expires_in` value from the Trakt api when authenticating and storing it to check when the token should be refreshed.
- Fix time remaining issues for api request errors

Address new OAuth Trakt access_token expiration changes

---

IMDBTraktSyncer/IMDBTraktSyncer.py
pyproject.toml

- Fix for #174 fixes an issue where `ValueError` was raised when updating existing IMDB ratings causing the script to fail. The error was due to page layout changes where the rating element is loaded in dynamically, and required the use of `.get_attribute("textContent")` instead of `.text` in order to get the rating element text. Also added ValueError check so that if this section of code breaks in the future due to layout changes it won't cause the entire script to fail.

Fix for ValueError when updating existing IMDB ratings

---

IMDBTraktSyncer/imdbData.py
pyproject.toml

- Fix for #180 fixes an Exception error when generating IMDB exports with empty IMDB account which has no ratings, watchlist or check-in items to generate from the IMDB exports page

Fix for error when generating IMDB exports with empty IMDB account

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
pyproject.toml

- Fixed an issue where some IMDB reviews were omitted from comparison with Trakt reviews due to None Type attribute returned from Trakt api. This was causing some reviews to be resubmitted to IMDB.
- Fixed an issue where reviews resubmitted to IMDB that already have an existing review would duplicate the title and body fields, now it will clear the fields properly before submitting, and also skip submitting a review if one already exists (it shouldn't be resubmitting anything anyway unless there is issue upstream like the issue mentioned above)
- Added new filter for comparing trakt and imdb review lists to remove unknown types

Fix for syncing reviews
