IMDbTraktSyncer/IMDbTraktSyncer.py

https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/7
https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/6

Issue with Trakt movie ratings not being set + add x of x functionality 

---

IMDbTraktSyncer/IMDbTraktSyncer.py
IMDbTraktSyncer/authTrakt.py
IMDbTraktSyncer/imdbRatings.py
IMDbTraktSyncer/traktRatings.py
IMDbTraktSyncer/verifyCredentials.py
setup.py

- Consolidate scripts and use import function method rather than running a separate python interpreter for subprocess.run
- Remove redundant lines of code
- Remove unnecessary comments

Clean up code and increase performance

---

IMDbTraktSyncer/IMDbTraktSyncer.py
IMDbTraktSyncer/imdbRatings.py
IMDbTraktSyncer/traktRatings.py
IMDbTraktSyncer/verifyCredentials.py
setup.py

Having an equal sign (=) as password will break the script. Change the credential file to use a standardized format, like INI, XML, JSON, YAML, TOML, etc. https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/1
Improve script performance. Remove redundant code. Remove double IMDB login. https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/10

Fix multiple issues and improve script performance

---

IMDbTraktSyncer/IMDbTraktSyncer.py

https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/12

Disable save password bubble

---

IMDbTraktSyncer/IMDbTraktSyncer.py
setup.py

- Add detailed error handling for not signed in catpcha required https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/2 and wrong chromedriver version https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/16
- Modify code to work with foreign browser language on IMDb website (previously any language other than English would break the code)
- Modify code for setting IMDb and Trakt rating loops to only run when there are ratings to set (increase performance)
- Add logging to modify console output to remove dev tools listening line

Add detailed error handling and foreign browser language support

---

IMDbTraktSyncer/imdbRatings.py

- Modify code to add more strict selection of deleting ratings.csv file by checking the file name for "ratings". This is to avoid unwanted .csv files in the same folder from being deleted by the script.

Improve IMDb ratings file deletion handling

---

IMDbTraktSyncer/IMDbTraktSyncer.py
IMDbTraktSyncer/imdbRatings.py
IMDbTraktSyncer/traktRatings.py
setup.py

- Add support for episode ratings https://github.com/RileyXX/IMDb-Trakt-Syncer/issues/14
_Note: Season ratings are not supported on IMDb, therefore season ratings sync can not be implemented._

Add support for episode ratings

---

IMDbTraktSyncer/IMDbTraktSyncer.py
IMDbTraktSyncer/authTrakt.py
IMDbTraktSyncer/traktRatings.py
IMDbTraktSyncer/verifyCredentials.py
setup.py

- Minor fixes: Remove unnecessary imports 
- Strip user entered credentials of whitespaces before saving to credentials.txt

Minor fixes: Remove unnecessary imports and strip user entered credentials of whitespaces before saving to credentials.txt

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
setup.py

* Modified requests to use error handling functions
* Add more other status codes to retry when failed. (e.g. API down for maintenance and other unavailable errors)
* Add more detailed status code descriptions from Trakt api. This will help with troubleshooting if an api request failed.

Improve api status code handling

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

- Use graceful method for retrieving data from api response. This will prevent any items with missing data from breaking the script.
- Use except ImportError: instead of except:
- Add alternate package name for some imported packages for easier reading

Minor improvements. Use graceful method for retrieving data from api response

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
setup.py

- Add more thorough check to see if there were errors getting IMDB reviews then skip reviews submissions to avoid duplicate reviews being submitted.

Add more thorough check if errors getting IMDB reviews then skip reviews submissions

---

IMDBTraktSyncer/errorHandling.py
setup.py

- Fix for missing import in errorHandling.py

Fix for missing import

---

IMDBTraktSyncer/authTrakt.py
setup.py

- Fix for circular import bug on first time Trakt authorization. This bug appears to have been introduced in v1.2.1.

Fix for circular import bug on first time Trakt authorization

---

IMDBTraktSyncer/authTrakt.py
setup.py

- Fix for potential circular import bug which appears to have been added in v1.1.0

Fix for circular import bug

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
setup.py

- Potential fix for https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/42
- Modify some elements to use `element_to_be_clickable` instead of `presence_of_element_located` to avoid errors when clicking an element before it becomes clickable
- Add `scrollIntoView` using JavaScript method for multiple elements where the element may be out of view
- Modify clicking the watchlist button to JavaScript click method

Fix for errors while clicking some elements when they are out of view or have not fully loaded "ElementClickInterceptedException"

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
IMDBTraktSyncer/verifyCredentials.py
README.md
setup.py

- Add support for optional setting to remove watched items. https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/44
- Potential fix for watchlist/rating file invalid character decoding error in https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/46.
- Modify opening credentials file to use `utf-8` encoding.
- Clean up `verifyCredentials.py` by modifying the code so all variables are returned from functions.
- Modify all instances of the `'ID'` variable to use `'IMDB_ID'` instead to make the code easier to understand.
- Modify getting reviews from `traktData.py` and `imdbData.py` so that duplicates are removed before returning the `getTraktData()` and `getImdbData()` functions. This will allow an easier and cleaner approach to sorting items in `IMDBTraktSyncer.py`.

Add optional setting to remove watched items from watchlists + other fixes

---

IMDBTraktSyncer/IMDBTraktSyncer.py
setup.py

- Fix for ratings still syncing even when disabled. Bug was introduced in [v1.4.0](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.4.0) when the new rating sync setting was implemented.

Fix for ratings still syncing even when disabled

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorLogger.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

- Minor fixes for log file location
- Fix for missing variable in `check_imdb_reviews_last_submitted()` - `verifyCredentials.py`

Minor fixes for error log file location

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/errorLogger.py
IMDBTraktSyncer/imdbData.py
setup.py

- IMDB requests are now passed with the wait variable to improve the flow of the code
- More selenium imports are added to `errorHandling.py` and `imdbData.py` to avoid potential errors
- Unnecessary logger definition for `selenium.webdriver` in `errorLogger.py` is removed

Minor changes to IMDB requests and error logger

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
setup.py

- IMDB url requests now pulls the status code directly from the browser rather than making extra unnecessary requests (improve performance). 
- Improvements for printing item status.

Improvements for IMDB requests and printing item status

---

IMDBTraktSyncer/imdbData.py
setup.py

- Minor improvements for getting IMDB reviews

Minor improvements for getting IMDB reviews

---

IMDBTraktSyncer/checkChromedriver.py
setup.py

Modify chromedriver check fallback method to fix a couple of potential issues with getting the version title.

Minor changes to chromedriver check fallback method

---

IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

- Fix for some Trakt auth requests failing. This bug was causing the script to fail occasionally when authorizing Trakt. This was due to the script not handling failed requests and retrying where necessary in `authTrakt.py`. It now handles these requests properly.
- Improvements for handling credentials in `verifyCredentials.py`

Fix for some Trakt auth requests failing occasionally + other minor improvements

---

IMDBTraktSyncer/authTrakt.py
setup.py

- Script now prompts the user to reauthenticate if the user's refresh token has expired or is invalid.

Improvements for handling invalid Trakt refresh token

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/checkVersion.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

- Fix for IMDB data processing for versions 1.8.7 and below as mentioned in: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/88. 
- Added version checker which prompts the user when running the script if a new update is available.
- Script now prints out the directory where the user's credentials and log files are located. This will make it easier for the user to make any necessary changes. As mentioned in: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/87.

Fix for IMDB data processing + other minor changes

---

IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/verifyCredentials.py
setup.py

This pull request implements a fix for a change in the IMDB CSV data structure for ratings and watchlist csv file exports from https://www.imdb.com/exports which were causing syncing to fail. The script should now handle the new CSV data structure and with added checks to prevent the script from running should the data structure change again in the future.
Special thanks to [@paulgendek](https://github.com/paulgendek) for finding this bug as mentioned in: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/93
Possible fix for: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/92

Fix for change in IMDB CSV data structure causing syncing to fail

---

IMDBTraktSyncer/checkVersion.py
setup.py

This pull request fixes an issue where the newly implemented version checker was being skipped. The script should now check the version and prompt the user when a new update is available.

Minor fix for version checker

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
README.md
setup.py

- Added support for multi-language IMDB settings. A previous fix https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/93 addressed an issue where the IMDB ratings and watchlist .csv data structure changed. The fix, while future proofed against future .csv data structure changes, it didn't account for users with other languages other than English. This problem is now fixed. The script will temporarily change the users IMDB language to English for compatibility, and then change it back to the users original language after completing.
- Attempts to fix an issue with driver element not clickable error on Mac OS when script downloads watchlist/ratings .csv export file.
- Script now ignores syncing items with unknown categories.
- Script now prints IMDB ID for all items

Various fixes and improvements. IMDB multi-language support. Fix for items with unknown categories & more.

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/arguments.py
IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/checkChrome.py
IMDBTraktSyncer/errorHandling.py
setup.py

Referenced issues:
- https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/121
- https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/119
Please see the following comment for more information regarding this bug: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/121#issuecomment-2577513043
- https://issues.chromium.org/issues/386887881 
- https://issues.chromium.org/issues/386887881

Fix for Chromium bug page timeouts + other minor improvements

---

IMDBTraktSyncer/authTrakt.py
IMDBTraktSyncer/errorHandling.py
setup.py

Issue where valid Trakt re-authentication requests were being retried.

Fix Trakt re-authentication retry response bug

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/arguments.py
IMDBTraktSyncer/checkChrome.py
IMDBTraktSyncer/checkVersion.py
IMDBTraktSyncer/traktData.py
IMDBTraktSyncer/verifyCredentials.py
LICENSE
README.md
pyproject.toml

- Script now handles chromedriver downloads internally. This gives more control over browser and driver downloads instead of relying on selenium's built in selenium manager or other third party tools such as webdriver-manager or chromedriver-py. This should eliminate many problems such as driver mismatches.
- Fix bug when submitting IMDB reviews: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/128
- Removed `setup.py` file in favor of more modern `pyproject.toml` file for handling Python package installs
- Other minor changes

Improve chromedriver handling, fix bug when submitting IMDB reviews, remove setup.py in favor of modern pyproject.toml & other minor improvements

---

IMDBTraktSyncer/checkChrome.py
pyproject.toml

- Fix issue where additional subfolder was missing in macOS special case for Chrome browser path
- Added cleanup in extracted chromedriver folder for unecessary files

Fix additional pathing issues on linux and macos

---

IMDBTraktSyncer/checkChrome.py
IMDBTraktSyncer/errorHandling.py
pyproject.toml

- Additional fixes for permissions issues. Apply grant_permissions every time running the script to avoid permissions issues with older installs, and modified directories.
- Fix `stat` missing import in `checkChrome.py`
- Improve error handling retries for IMDB page load requests, correctly retry retryable errors such as `ERR_CLOSED_CONNECTION`

Additional fixes for permissions issues, fix import error, improve error handling retries for IMDB page load requests

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
pyproject.toml

- Possible fix selenium exception: invalid session id as reported: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/116#issuecomment-2597045399
- Return driver variable back from `get_page_with_retries()` function to avoid holding a reference to an invalid or outdated WebDriver session on future page loads

Improvements for driver handling

---

IMDBTraktSyncer/IMDBTraktSyncer.py
pyproject.toml

Fix issue where chromedriver runs in non-headless mode

Fix issue where chromedriver runs in non-headless mode

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/imdbData.py
IMDBTraktSyncer/traktData.py
IMDBTraktSyncer/verifyCredentials.py
pyproject.toml

- Added feature: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/118
- Added feature: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/103
- Code cleanup
- Improved processing of user data. The script now only processes the necessary data needed for the settings the user provided, skipping unnecessary steps.

Added sync watch history feature, added mark rated as watched feature, code cleanup, improved data processing

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/checkChrome.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/traktData.py
README.md
pyproject.toml

- Added wait time after downloading chrome/chromedriver to avoid extracting/moving too early and corrupting files
- Potential fix for https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/142
- Other minor improvements

Changes to chrome/chromedriver download handling, bug fixes and other minor improvements

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/verifyCredentials.py
pyproject.toml

- Remove 10,000 limit for IMDB ratings since this limit is not enforced by IMDB, per request: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/145
- Add option to remove watchlist items after x days https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/144
- Improvements to printing log items when adding/removing items
- Fix for mentioned comment: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/116#issuecomment-2608400135
- Other minor changes

Remove 10,000 limit for IMDB ratings, add option to remove watchlist items after x days + other minor improvements

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/errorHandling.py
IMDBTraktSyncer/verifyCredentials.py
pyproject.toml

- Fixes recurring prompt bug for remove watchlist after x days
- Move filter lists already set logic to its own function

Fix prompt for remove watchlist after x days, move filter lists already set to function

---

IMDBTraktSyncer/IMDBTraktSyncer.py
pyproject.toml

- Fixed an issue where trakt items with None type value for IMDB_ID were processed as "outdated" causing PageLoad exception errors such as `PageLoadException: Failed to load page. Status code: 404. URL: https://www.imdb.com/title/None/ URL: https://www.imdb.com/title/None/ (File: errorHandling.py, Line: 269)`
- Added retries when downloading chrome/chromedriver to account for failures during the download or extraction process

Fix issue when updating outdated trakt imdb ids with None type value, add retries for downloading chrome/chromedriver

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/verifyCredentials.py
pyproject.toml

- Fix for `check_imdb_reviews_last_submitted()` function which was moved in a previous version. As reported in: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/163

Fix for syncing IMDB reviews

---

IMDBTraktSyncer/imdbData.py
pyproject.toml

- Fix for #182 fixes an UnboundLocalError when checking the size of empty IMDB watchlist & checkin lists

Fix UnboundLocalError checking empty IMDB watchlist & checkin size

---

IMDBTraktSyncer/IMDBTraktSyncer.py
IMDBTraktSyncer/imdbData.py
pyproject.toml

- Fixes issue where no IMDB reviews are found due to IMDB reviews page layout changes. This was causing reviews to be resubmitted as edits on IMDB.

Fix bugs when processing IMDB reviews due to page layout changes

---

IMDBTraktSyncer/IMDBTraktSyncer.py
pyproject.toml

- Uses a new more direct method for finding the IMDB signin link which should improve reliability and limit potential script failing when IMDB signin link is not located

Improvements when signing into IMDB
